/**
 * One-time generator: compute hardcoded face-array baselines for cube-alg-states.test.ts.
 *
 * Run once, paste output into the test file as const BASELINES.
 * Re-run only if CubeState.toFaceArray() implementation changes.
 *
 * Usage: npx tsx packages/cubify/scripts/gen-alg-baselines.ts
 */

import { CubeState } from '../src/CubeState.js';

const CASES: Array<{ id: string; alg: string; rotation: string; direct?: boolean }> = [
  { id: 'sune',      alg: "R U R' U R U2 R'",                           rotation: 'z2' },
  { id: 'antisune',  alg: "R U2 R' U' R U' R'",                         rotation: 'z2' },
  { id: 'h_shape',   alg: "R U R' U R U' R' U R U2 R'",                 rotation: 'z2' },
  { id: 'pi_shape',  alg: "R U2 R2 U' R2 U' R2 U2 R",                   rotation: 'z2' },
  { id: 'line',      alg: "F R U R' U' F'",                             rotation: 'z2' },
  { id: 'hook',      alg: "f R U R' U' f'",                             rotation: 'z2' },
  { id: 't_perm',    alg: "R U R' U' R' F R2 U' R' U' R U R' F'",       rotation: 'z2' },
  { id: 'ua_perm',   alg: "R2 U' R' U' R U R U R U' R",                 rotation: 'z2' },
  { id: 'h_perm',    alg: "M2 U' M2 U2 M2 U' M2",                       rotation: 'z2 y2' },
  { id: 'superflip', alg: "U R2 F B R B2 R U2 L B2 R U' D' R2 F R' L B2 U2 F2", rotation: '', direct: true },
];

async function main() {
  const solved = await CubeState.solved();

  console.log('// AUTO-GENERATED by gen-alg-baselines.ts — do not edit by hand');
  console.log('// Re-run only if CubeState.toFaceArray() implementation changes.\n');
  console.log('export const BASELINES: Record<string, string[][]> = {');

  for (const { id, alg, rotation, direct } of CASES) {
    const caseState = direct
      ? solved.applyAlg(alg)
      : solved.applyAlg(CubeState.setupFromAlg(alg, rotation));
    const faces = caseState.toFaceArray();

    // Verify invariant before hardcoding
    const afterAlg = direct
      ? caseState.applyAlg(alg)          // self-inverse: apply twice = solved
      : caseState.applyAlg(alg);
    if (!afterAlg.isSolved()) {
      console.error(`ERROR: ${id} — invariant failed! Check alg/rotation.`);
      process.exit(1);
    }

    const rows = faces.map(f => `    ${JSON.stringify(f)},`).join('\n');
    console.log(`  ${id}: [`);
    console.log(rows);
    console.log('  ],');
  }

  console.log('};');
}

main().catch(err => { console.error(err); process.exit(1); });
