/**
 * cube-alg-states.test.ts — per-sticker regression tests for CFOP case recognition.
 *
 * Motivation: setupFromAlg + invertAlg have caused repeated production bugs.
 * These tests snapshot exact face arrays for the 2-look OLL/PLL alg set
 * (source of truth: cfop-app/public/data/algs-cfop-bgr.json).
 *
 * Baselines are pre-computed once from CubeState (cubing.js ground truth) and hardcoded.
 * Re-generate with: npx tsx packages/cubify/scripts/gen-alg-baselines.ts
 *
 * Face order: U=0, R=1, F=2, D=3, L=4, B=5
 * Sticker layout per face (reading order):  0 1 2 / 3 4 5 / 6 7 8
 *
 * Convention: setup = z2 + invertAlg(alg) — cube starts D-face up (solved D on top),
 * then alg is applied, leaving U solved. Invariant: caseState.applyAlg(alg).isSolved().
 */

import { describe, it, expect, beforeAll } from 'vitest';
import { CubeState } from '../src/CubeState.js';

// ── Hardcoded baselines ────────────────────────────────────────────────────────
// AUTO-GENERATED by gen-alg-baselines.ts — do not edit by hand.
// Re-run the script if CubeState.toFaceArray() changes.
const BASELINES: Record<string, string[][]> = {
  sune: [
    ["L","D","F","D","D","D","D","D","R"],
    ["B","B","D","L","L","L","L","L","L"],
    ["B","F","D","F","F","F","F","F","F"],
    ["U","U","U","U","U","U","U","U","U"],
    ["F","L","L","R","R","R","R","R","R"],
    ["R","R","D","B","B","B","B","B","B"],
  ],
  antisune: [
    ["F","D","D","D","D","D","L","D","B"],
    ["D","R","R","L","L","L","L","L","L"],
    ["D","F","R","F","F","F","F","F","F"],
    ["U","U","U","U","U","U","U","U","U"],
    ["D","B","B","R","R","R","R","R","R"],
    ["F","L","L","B","B","B","B","B","B"],
  ],
  h_shape: [
    ["B","D","B","D","D","D","F","D","F"],
    ["D","R","D","L","L","L","L","L","L"],
    ["R","F","L","F","F","F","F","F","F"],
    ["U","U","U","U","U","U","U","U","U"],
    ["D","B","D","R","R","R","R","R","R"],
    ["L","L","R","B","B","B","B","B","B"],
  ],
  pi_shape: [
    ["F","D","R","D","D","D","B","D","R"],
    ["B","L","F","L","L","L","L","L","L"],
    ["L","B","D","F","F","F","F","F","F"],
    ["U","U","U","U","U","U","U","U","U"],
    ["D","F","D","R","R","R","R","R","R"],
    ["D","R","L","B","B","B","B","B","B"],
  ],
  line: [
    ["L","F","D","D","D","D","L","L","D"],
    ["F","B","B","L","L","L","L","L","L"],
    ["F","D","R","F","F","F","F","F","F"],
    ["U","U","U","U","U","U","U","U","U"],
    ["D","R","D","R","R","R","R","R","R"],
    ["R","D","B","B","B","B","B","B","B"],
  ],
  hook: [
    ["L","F","D","B","D","D","L","D","D"],
    ["F","L","B","L","L","L","L","L","L"],
    ["F","R","R","F","F","F","F","F","F"],
    ["U","U","U","U","U","U","U","U","U"],
    ["D","D","D","R","R","R","R","R","R"],
    ["R","D","B","B","B","B","B","B","B"],
  ],
  t_perm: [
    ["D","D","D","D","D","D","D","D","D"],
    ["B","R","F","L","L","L","L","L","L"],
    ["F","F","L","F","F","F","F","F","F"],
    ["U","U","U","U","U","U","U","U","U"],
    ["R","L","R","R","R","R","R","R","R"],
    ["L","B","B","B","B","B","B","B","B"],
  ],
  ua_perm: [
    ["D","D","D","D","D","D","D","D","D"],
    ["L","B","L","L","L","L","L","L","L"],
    ["F","F","F","F","F","F","F","F","F"],
    ["U","U","U","U","U","U","U","U","U"],
    ["R","L","R","R","R","R","R","R","R"],
    ["B","R","B","B","B","B","B","B","B"],
  ],
  h_perm: [
    ["D","D","D","D","D","D","D","D","D"],
    ["R","L","R","R","R","R","R","R","R"],
    ["B","F","B","B","B","B","B","B","B"],
    ["U","U","U","U","U","U","U","U","U"],
    ["L","R","L","L","L","L","L","L","L"],
    ["F","B","F","F","F","F","F","F","F"],
  ],
  superflip: [
    ["U","B","U","L","U","R","U","F","U"],
    ["R","U","R","F","R","B","R","D","R"],
    ["F","U","F","L","F","R","F","D","F"],
    ["D","F","D","L","D","R","D","B","D"],
    ["L","U","L","B","L","F","L","D","L"],
    ["B","U","B","R","B","L","B","D","B"],
  ],
};

// ── Test cases (alg strings match algs-cfop-bgr.json) ────────────────────────
const CASES: Array<{
  id: string;
  label: string;
  alg: string;
  rotation: string;
}> = [
  // 2-look OLL — corners
  { id: 'sune',     label: 'Sune',     alg: "R U R' U R U2 R'",           rotation: 'z2' },
  { id: 'antisune', label: 'AntiSune', alg: "R U2 R' U' R U' R'",         rotation: 'z2' },
  { id: 'h_shape',  label: 'H shape',  alg: "R U R' U R U' R' U R U2 R'", rotation: 'z2' },
  { id: 'pi_shape', label: 'Pi shape', alg: "R U2 R2 U' R2 U' R2 U2 R",   rotation: 'z2' },
  // 2-look OLL — edges
  { id: 'line',     label: 'Line',     alg: "F R U R' U' F'",             rotation: 'z2' },
  { id: 'hook',     label: 'Hook',     alg: "f R U R' U' f'",             rotation: 'z2' },
  // 2-look PLL
  { id: 't_perm',    label: 'T Perm',  alg: "R U R' U' R' F R2 U' R' U' R U R' F'",   rotation: 'z2' },
  { id: 'ua_perm',  label: 'Ua Perm',  alg: "R2 U' R' U' R U R U R U' R",             rotation: 'z2' },
  { id: 'h_perm',    label: 'H Perm',    alg: "M2 U' M2 U2 M2 U' M2",                                    rotation: 'z2 y2' },
  { id: 'superflip', label: 'Superflip', alg: "U R2 F B R B2 R U2 L B2 R U' D' R2 F R' L B2 U2 F2",  rotation: '' },
];

// ── Fixtures ──────────────────────────────────────────────────────────────────

let solved: CubeState;

beforeAll(async () => {
  solved = await CubeState.solved();
});

// ── Category 1: invertAlg unit tests ─────────────────────────────────────────

describe('invertAlg', () => {
  it('inverts a single prime move: R\' → R', () => {
    expect(CubeState.invertAlg(["R'"])).toEqual(['R']);
  });

  it('inverts a single move: R → R\'', () => {
    expect(CubeState.invertAlg(['R'])).toEqual(["R'"]);
  });

  it('preserves double moves: R2 → R2', () => {
    expect(CubeState.invertAlg(['R2'])).toEqual(['R2']);
  });

  it('reverses sequence order: R U R\' → R U\' R\'', () => {
    expect(CubeState.invertAlg(['R', 'U', "R'"])).toEqual(['R', "U'", "R'"]);
  });

  it('inverts full Sune: R U R\' U R U2 R\' → R U2 R\' U\' R U\' R\'', () => {
    const moves = ["R", "U", "R'", "U", "R", "U2", "R'"];
    expect(CubeState.invertAlg(moves)).toEqual(["R", "U2", "R'", "U'", "R", "U'", "R'"]);
  });

  it('applying alg then its inverse returns to solved state', async () => {
    const alg = ["R", "U", "R'", "U'"];
    const inv = CubeState.invertAlg(alg);
    const state = solved.applyAlg(alg).applyAlg(inv);
    expect(state.isSolved()).toBe(true);
  });

  it('applying inverse then alg returns to solved state', async () => {
    const alg = "R U R' U R U2 R'";
    const inv = CubeState.invertAlg(alg.split(' '));
    const state = solved.applyAlg(inv).applyAlg(alg.split(' '));
    expect(state.isSolved()).toBe(true);
  });
});

// ── Category 2: setupFromAlg unit tests ──────────────────────────────────────

describe('setupFromAlg', () => {
  it('without rotation: returns just the inverse', () => {
    const result = CubeState.setupFromAlg("R U R' U R U2 R'");
    expect(result).toBe("R U2 R' U' R U' R'");
  });

  it('with z2 rotation: prepends rotation to inverse', () => {
    const result = CubeState.setupFromAlg("R U R' U R U2 R'", 'z2');
    expect(result).toBe("z2 R U2 R' U' R U' R'");
  });

  it('with multi-part rotation: prepends full rotation string', () => {
    const result = CubeState.setupFromAlg("M2 U' M2 U2 M2 U' M2", 'z2 y2');
    expect(result).toBe("z2 y2 M2 U M2 U2 M2 U M2");
  });

  it('applying setupFromAlg then alg on solved returns solved (Sune)', async () => {
    const alg = "R U R' U R U2 R'";
    const setup = CubeState.setupFromAlg(alg, 'z2');
    const caseState = solved.applyAlg(setup);
    expect(caseState.applyAlg(alg).isSolved()).toBe(true);
  });

  it('applying setupFromAlg then alg on solved returns solved (T Perm)', async () => {
    const alg = "R U R' U' R' F R2 U' R' U' R U R' F'";
    const setup = CubeState.setupFromAlg(alg, 'z2');
    const caseState = solved.applyAlg(setup);
    expect(caseState.applyAlg(alg).isSolved()).toBe(true);
  });
});

// ── Category 3: Case-state snapshots ─────────────────────────────────────────
//
// For each alg: the case state (solved.applyAlg(setupFromAlg(alg, rotation)))
// must exactly match the hardcoded baseline AND applying the alg must solve it.

describe('case state snapshots', () => {
  for (const { id, label, alg, rotation } of CASES) {
    describe(label, () => {
      let caseState: CubeState;

      beforeAll(async () => {
        const setup = CubeState.setupFromAlg(alg, rotation);
        caseState = solved.applyAlg(setup);
      });

      it('face array matches hardcoded baseline', () => {
        expect(caseState.toFaceArray()).toEqual(BASELINES[id]);
      });

      it('applying alg solves the case', () => {
        expect(caseState.applyAlg(alg).isSolved()).toBe(true);
      });
    });
  }
});

